export const authConstants = {
    USER_SIGNUP_REQUEST:'USER_SIGNUP_REQUEST',
    USER_SIGNUP_SUCCESS:'USER_SIGNUP_SUCCESS',
    USER_SIGNUP_FAILURE:'USER_SIGNUP_FAILURE',

    USER_LOGIN_REQUEST:'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS:'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE:'USER_LOGIN_FAILURE',

    GET_ALL_USER_SUCCESS:'GET_ALL_USER_SUCCESS',
}

export const photoConstants = {
    PHOTO_GET_REQUEST:'PHOTO_GET_REQUEST',
    PHOTO_GET_SUCCESS:'PHOTO_GET_SUCCESS',
    PHOTO_GET_FAILURE:'PHOTO_GET_FAILURE',

    PHOTO_POST_REQUEST:'PHOTO_POST_REQUEST',
    PHOTO_POST_SUCCESS:'PHOTO_POST_SUCCESS',
    PHOTO_POST_FAILURE:'PHOTO_POST_FAILURE',

    PHOTO_UPDATE_REQUEST:'PHOTO_UPDATE_REQUEST',
    PHOTO_UPDATE_SUCCESS:'PHOTO_UPDATE_SUCCESS',
    PHOTO_UPDATE_FAILURE:'PHOTO_UPDATE_FAILURE',
}
export const categoryConstants = {
    GET_ALL_CATEGORY_REQUEST:'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_SUCCESS:'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILURE:'GET_ALL_CATEGORY_FAILURE',

}