export const authConstants = {
    USER_SIGNUP_REQUEST:'USER_SIGNUP_REQUEST',
    USER_SIGNUP_SUCCESS:'USER_SIGNUP_SUCCESS',
    USER_SIGNUP_FAILURE:'USER_SIGNUP_FAILURE',

    USER_LOGIN_REQUEST:'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS:'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE:'USER_LOGIN_FAILURE',

    GET_ALL_USER_SUCCESS:'GET_ALL_USER_SUCCESS',
}

 
export const categoryConstants = {
    GET_ALL_CATEGORY_REQUEST:'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_SUCCESS:'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILURE:'GET_ALL_CATEGORY_FAILURE',
}

export const roomConstants = {
    GET_ALL_ROOM_REQUEST:'GET_ALL_ROOM_REQUEST',
    GET_ALL_ROOM_SUCCESS:'GET_ALL_ROOM_SUCCESS',
    GET_ALL_ROOM_FAILURE:'GET_ALL_ROOM_FAILURE',

    BOOK_ROOM_REQUEST:'BOOK_ROOM_REQUEST',
    BOOK_ROOM_SUCCESS:'BOOK_ROOM_SUCCESS',
    BOOK_ROOM_FAILURE:'BOOK_ROOM_FAILURE',
}