export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',

    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
    USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
    USER_SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',
    USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS'

}

export const categoryConstants = {
    GET_CATEGORY_REQUEST : 'GET_CATEGORY_REQUEST',
    GET_CATEGORY_SUCCESS : 'GET_CATEGORY_SUCCESS',
    GET_CATEGORY_FAILURE : 'GET_CATEGORY_FAILURE',

    ADD_CATEGORY_REQUEST : 'ADD_CATEGORY_REQUEST',
    ADD_CATEGORY_SUCCESS : 'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAILURE : 'ADD_CATEGORY_FAILURE',

    UPDATE_CATEGORIES_REQUEST : 'UPDATE_CATEGORIES_REQUEST',
    UPDATE_CATEGORIES_SUCCESS : 'UPDATE_CATEGORIES_SUCCESS',
    UPDATE_CATEGORIES_FAILURE : 'UPDATE_CATEGORIES_FAILURE',

    DELETE_CATEGORIES_REQUEST : 'DELETE_CATEGORIES_REQUEST',
    DELETE_CATEGORIES_SUCCESS : 'DELETE_CATEGORIES_SUCCESS',
    DELETE_CATEGORIES_FAILURE : 'DELETE_CATEGORIES_FAILURE',

}

export const productConstants = {
    GET_PRODUCT_REQUEST : 'GET_PRODUCT_REQUEST',
    GET_PRODUCT_SUCCESS : 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAILURE : 'GET_PRODUCT_FAILURE',

    DELETE_PRODUCT_BY_ID_REQUEST: "DELETE_PRODUCT_BY_ID_REQUEST",
    DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
    DELETE_PRODUCT_BY_ID_FAILURE: "DELETE_PRODUCT_BY_ID_FAILURE",

    ADD_PRODUCT_REQUEST : 'ADD_PRODUCT_REQUEST',
    ADD_PRODUCT_SUCCESS : 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILURE : 'ADD_PRODUCT_FAILURE'
}

export const initialDataConstants = {
    GET_INITIALDATA_REQUEST : 'GET_INITIALDATA_REQUEST',
    GET_INITIALDATA_SUCCESS : 'GET_INITIALDATA_SUCCESS',
    GET_INITIALDATA_FAILURE : 'GET_INITIALDATA_FAILURE',
}

export const pageConstants = {
    CREATE_PAGE_REQUEST:'CREATE_PAGE_REQUEST',
    CREATE_PAGE_SUCCESS:'CREATE_PAGE_SUCCESS',
    CREATE_PAGE_FAILURE:'CREATE_PAGE_FAILURE',
}

export const orderConstants = {
    GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
    GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
    GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",
  
    UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
    UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
    UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
  };